pull_request_rules:
  - name: BB cross-tenant comment bot account control
    conditions:
      - title = BB COMMENT OAUTH CONTROL Q7N4
    actions:
      comment:
        message: BB_MERGIFY_OAUTH_CONTROL_Q7N4
        bot_account: onecursor5-design
